// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL3yu82QvrgRwR1Jwdi528wiRt0AOmado',
    appId: '1:703189352961:web:15f9053150da2361cc3600',
    messagingSenderId: '703189352961',
    projectId: 'neuroplan21',
    authDomain: 'neuroplan21.firebaseapp.com',
    storageBucket: 'neuroplan21.firebasestorage.app',
    measurementId: 'G-804GZF74Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJCwVUhdyY9tFL3jaKJBYV0msqVuLVMBM',
    appId: '1:703189352961:android:37c4dead976b1a72cc3600',
    messagingSenderId: '703189352961',
    projectId: 'neuroplan21',
    storageBucket: 'neuroplan21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIRPeaufHf0L0AobgDVcq1umV4_mLdThc',
    appId: '1:703189352961:ios:8144f27afd5f8368cc3600',
    messagingSenderId: '703189352961',
    projectId: 'neuroplan21',
    storageBucket: 'neuroplan21.firebasestorage.app',
    iosClientId: '703189352961-r463snfkjuf6b4hi1u79b8lf42gbj7d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIRPeaufHf0L0AobgDVcq1umV4_mLdThc',
    appId: '1:703189352961:ios:8144f27afd5f8368cc3600',
    messagingSenderId: '703189352961',
    projectId: 'neuroplan21',
    storageBucket: 'neuroplan21.firebasestorage.app',
    iosClientId: '703189352961-r463snfkjuf6b4hi1u79b8lf42gbj7d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.neuroplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL3yu82QvrgRwR1Jwdi528wiRt0AOmado',
    appId: '1:703189352961:web:38b77561138d4de3cc3600',
    messagingSenderId: '703189352961',
    projectId: 'neuroplan21',
    authDomain: 'neuroplan21.firebaseapp.com',
    storageBucket: 'neuroplan21.firebasestorage.app',
    measurementId: 'G-3DH3N2FNL8',
  );
}
